Remove unused kubeClientSet in agent Controller
submariner-io/lighthouse pull request #1027
Opened 2023-01-03 16:42 UTC by tpantelis

2023-01-03 16:51 UTC, skitt requested changes

2023-01-03 16:51 UTC, skitt commented on pkg/agent/controller/controller_suite_test.go
>  	endpointsReactor         *fake.FailingReactor
This is unused too.

2023-01-03 17:22 UTC, skitt approved these changes

2023-01-05 16:02 UTC, dfarrell07 approved these changes

2023-01-06 04:25 UTC, merged