Bump mellium.im/sasl to fix CVE-2022-48195
submariner-io/lighthouse pull request #1041
Opened 2023-01-12 14:39 UTC by dfarrell07

I don't think we're actually impacted by this as we're not connecting to untrusted endpoints, but we shouldn't need to trust endpoints.

Decription of CVE:

An issue was discovered in Mellium mellium.im/sasl before 0.3.1. When performing SCRAM-based SASL authentication, if the remote end advertises support for channel binding, no random nonce is generated (instead, the nonce is empty). This causes authentication to fail in the best case, but (if paired with a remote end that does not validate the length of the nonce) could lead to insufficient randomness being used during authentication.

https://mellium.im/cve/cve-2022-48195/

Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

2023-01-12 15:10 UTC, dfarrell07 commented
> Summarizing 1 Failure:
  [FAIL] EndpointSlice controller when a service has a valid endpoint when IsHealthy is called for the service with a valid cluster [It] should return true
  /go/src/github.com/submariner-io/lighthouse/coredns/endpointslice/controller_test.go:174

Not sure what's going on with the UTs.

2023-01-12 15:39 UTC, dfarrell07 commented
This issue also exists for Submariner 0.14, but not older releases.

2023-01-12 16:10 UTC, dfarrell07 commented
Three runs of the UTs and the same failure each time. Any idea @vthapar?

2023-01-12 16:14 UTC, tpantelis commented
> Three runs of the UTs and the same failure each time. Any idea @vthapar?

I can repro locally.  It looks like an intermittent timing issue related to fake clients - it goes away if I add a small delay in the test.

2023-01-12 16:42 UTC, dfarrell07 commented
Two weird things about this:
* The mellium.im/sasl dep is only in go.sum, so I don't think it should actually be used. 
* The CVE was also flagged for the main lighthouse mod, which has no reference to mellium.im/sasl.

2023-01-12 16:53 UTC, tpantelis commented
> I can repro locally. It looks like an intermittent timing issue related to fake clients - it goes away if I add a small delay in the test.

Fixed by https://github.com/submariner-io/lighthouse/pull/1042.

2023-01-13 00:07 UTC, skitt requested changes
This is a false positive, nothing in our code or in any of our dependencies’ packages we actually use, uses `mellium.im/sasl` (for proof of that, `make licensecheck` shows all the modules providing packages that end up in our binaries). [`go.sum`](https://go.dev/ref/mod#go-sum-files) is only a repository of digests, representing the full module dependency tree, and doesn’t reflect the modules which are really used; those are listed exhaustively in `go.mod`.

2023-01-13 15:47 UTC, closed without merging