Honor publishNotReadyAddresses flag for headless services
submariner-io/lighthouse pull request #1241
Opened 2023-05-24 15:46 UTC by tpantelis

For headless services, K8s does not publish DNS records for pods that are not ready unless `publishNotReadyAddresses` is set to true on the `Service`. The documentation for this flags states the "_the primary use case for setting this field is for a StatefulSet's Headless Service to propagate SRV DNS records for its Pods for the purpose of peer discovery. The Kubernetes controllers that generate Endpoints and EndpointSlice resources for Services interpret this to mean that all endpoints are considered "ready" even if the Pods themselves are not_".

Submariner previously did publish DNS records for pods that are not ready but was changed not do to so by https://github.com/submariner-io/lighthouse/issues/1090. However that issue really pertained to Cluster IP services where the K8s behavior is to resolve the service even if no backing pod is ready. This PR honors the `publishNotReadyAddresses` flag for headless services.

For the implementation, a new annotation, `lighthouse.submariner.io/publish-not-ready-addresses`, is introduced to propagate the `Service`'s `publishNotReadyAddresses` flag to the `EndpointSlice` via the local `ServiceImport`. See individual commits for more details.

2023-05-25 12:48 UTC, skitt approved these changes

2023-05-25 13:17 UTC, vthapar requested changes
Changes look good, testing locally. Just a small nit regarding a comment.

2023-05-25 13:17 UTC, vthapar commented on coredns/resolver/endpoint_slice.go
>  		// Skip if not ready. Note: we're treating nil as ready to be on the safe side as the EndpointConditions doc
nit: Update the comment to reflect the new check.

2023-05-26 13:46 UTC, aswinsuryan approved these changes

2023-05-31 07:47 UTC, vthapar approved these changes

2023-05-31 12:21 UTC, merged