Log version in lighthouse pods
submariner-io/lighthouse pull request #1287
Opened 2023-06-20 14:21 UTC by vthapar

Log version for Lighthoue agent and coredns pods on startup.

Fixes #1279

2023-06-20 14:35 UTC, skitt requested changes

2023-06-20 14:35 UTC, skitt commented on Makefile
> +export LDFLAGS = -X main.VERSION=$(VERSION)
```suggestion
export LDFLAGS = -X main.version=$(VERSION)
```

2023-06-20 14:35 UTC, skitt commented on coredns/main.go
> +var VERSION = "not-compiled-properly"
```suggestion
var version = "not-compiled-properly"
```

2023-06-20 14:35 UTC, skitt commented on coredns/main.go
> +	lighthouse.VERSION = VERSION
```suggestion
	lighthouse.Version = version
```

2023-06-20 14:35 UTC, skitt commented on coredns/plugin/setup.go
> +	VERSION    string
```suggestion
	Version    string
```

2023-06-20 14:35 UTC, skitt commented on coredns/plugin/setup.go
> +	log.Infof("submariner-lighthouse-coredns version: %v", VERSION)
```suggestion
	log.Infof("submariner-lighthouse-coredns version: %v", Version)
```

2023-06-20 14:35 UTC, skitt commented on pkg/agent/main.go
> +	VERSION    = "not-compiled-properly"
```suggestion
	version    = "not-compiled-properly"
```

2023-06-20 14:35 UTC, skitt commented on pkg/agent/main.go
> +	logger.Infof("Starting submariner-lighthouse-agent version: %v", VERSION)
```suggestion
	logger.Infof("Starting submariner-lighthouse-agent version: %v", version)
```

2023-06-20 15:28 UTC, tpantelis commented on coredns/main.go
> +	lighthouse.VERSION = VERSION
Why don't we just do `log.Infof("submariner-lighthouse-coredns version: %v", version)` in `main` before L116 below?

2023-06-20 15:38 UTC, skitt submitted a review, later dismissed
Sorry, something else I didn’t notice earlier.

2023-06-20 15:38 UTC, skitt commented on pkg/agent/main.go
> +	logger.Infof("Starting submariner-lighthouse-agent version: %v", version)
Grammatically, this should be

```suggestion
	logger.Infof("Starting submariner-lighthouse-agent version %v", version)
```

but to keep it consistent with other version output, and perhaps simplify parsing should we want to extract this in `subctl`, let’s make it

```suggestion
	logger.Infof("submariner-lighthouse-agent version: %v", version)
```

2023-06-21 07:14 UTC, skitt approved these changes
In future, please don’t dismiss “stale” reviews when you address the changes requested — you can mark the changes resolved, but dismissing reviews should only be done if necessary to unblock a PR.

2023-06-21 12:38 UTC, aswinsuryan approved these changes

2023-06-21 19:04 UTC, tpantelis approved these changes

2023-06-21 19:22 UTC, merged