Delete stale EndpointSlices on restart
submariner-io/lighthouse pull request #1430
Opened 2023-11-01 15:47 UTC by tpantelis

If a local LH `EndpointSlices` exists but the corresponding `Service` doesn't exist, delete the `EndpointSlice`.

Also, a headless `Service` can have multiple `EndpointSlices` so reconcile the LH `EndpointSlices` on startup to handle a K8s `EndpointSlice` deleted while the controller wasn't running.

Fixes https://github.com/submariner-io/lighthouse/issues/1416

2023-11-01 17:05 UTC, aswinsuryan approved these changes

2023-11-02 06:27 UTC, vthapar approved these changes

2023-11-02 07:47 UTC, sridhargaddam commented on pkg/agent/controller/endpoint_slice.go
> +			err := c.syncer.GetLocalFederator().Delete(ctx, endpointSlice)
I hope this deletes the EndpointSlice from the Broker as well?

2023-11-02 07:55 UTC, sridhargaddam requested changes

2023-11-02 07:55 UTC, sridhargaddam commented on pkg/agent/controller/endpoint_slice.go
> +			err := c.syncer.GetLocalFederator().Delete(ctx, endpointSlice)
I hope this deletes the EndpointSlice from the Broker as well?

2023-11-02 07:55 UTC, sridhargaddam commented on pkg/agent/controller/reconciliation_test.go
> +				fmt.Println("*******EPS 1: ", resource.ToJSON(localEndpointSlice))
```suggestion

```

2023-11-02 11:56 UTC, tpantelis commented on pkg/agent/controller/endpoint_slice.go
> +			err := c.syncer.GetLocalFederator().Delete(ctx, endpointSlice)
yup - the admiral syncer does that.

2023-11-02 11:56 UTC, tpantelis commented on pkg/agent/controller/reconciliation_test.go
> +				fmt.Println("*******EPS 1: ", resource.ToJSON(localEndpointSlice))
oops

2023-11-02 12:08 UTC, sridhargaddam approved these changes

2023-11-02 12:09 UTC, merged