Bump shipyard and address golangci-lint v1.60.3 errors
submariner-io/lighthouse pull request #1631
Opened 2024-08-27 16:07 UTC by tpantelis

Specifically, gosec "integer overflow conversion" issues.

Depends on https://github.com/submariner-io/shipyard/pull/1715

2024-08-28 08:49 UTC, skitt requested changes
There’s no Shipyard bump in the affected module (it doesn’t depend on Shipyard).

2024-08-28 11:55 UTC, tpantelis commented
> There’s no Shipyard bump in the affected module (it doesn’t depend on Shipyard).

yeah as it turned out. I had thought it would be affected by the Shipyard E2E changes but it wasn't. Still it doesn't hurt to bump it but I'll remove it.

2024-08-28 18:12 UTC, dfarrell07 approved these changes

2024-08-29 12:39 UTC, skitt approved these changes

2024-08-29 12:54 UTC, merged