Set non zero TTL in dns replies
submariner-io/lighthouse pull request #296
Opened 2020-09-11 19:11 UTC by vthapar

Set default ttl of 5 in DNS response as 0 is not recommended.

TODO: Make TTL a configurable parameter

Signed-off-by: Vishal Thapar <5137689+vthapar@users.noreply.github.com>

2020-09-12 03:56 UTC, tpantelis requested changes

2020-09-12 03:56 UTC, tpantelis commented on plugin/lighthouse/handler.go
> +		record := &dns.A{Hdr: dns.RR_Header{Name: state.QName(), Rrtype: dns.TypeA, Class: state.QClass(), Ttl: 5}, A: net.ParseIP(ip).To4()}
```suggestion
		record := &dns.A{Hdr: dns.RR_Header{Name: state.QName(), Rrtype: dns.TypeA, Class: state.QClass(), Ttl: lh.ttl}, A: net.ParseIP(ip).To4()}
```

2020-09-14 07:11 UTC, skitt requested changes
The change itself seems fine, but could you use your real email address in your sign-off?

2020-09-14 07:55 UTC, vthapar commented
> The change itself seems fine, but could you use your real email address in your sign-off?

I've always used this for security/privacy reasons on github. Does this mess up any scripts?

2020-09-14 12:16 UTC, skitt approved these changes

2020-09-14 12:19 UTC, tpantelis approved these changes

2020-09-14 12:20 UTC, merged