E2e to verify lighthouse return cluster-ip from healthy service
submariner-io/lighthouse pull request #429
Opened 2021-01-08 06:09 UTC by aswinsuryan

Fixes: submariner-io/submariner#1041

Signed-off-by: Aswin Surayanarayanan <asuryana@redhat.com>

2021-01-08 13:26 UTC, tpantelis requested changes

2021-01-08 13:26 UTC, tpantelis commented on test/e2e/discovery/service_discovery.go
> +		It("should not resolve the service on the unhealthy cluster", func() {
```suggestion
	When("only one of the clusters with a service is healthy", func() {
		It("should not resolve the service", func() {
```

2021-01-08 13:26 UTC, tpantelis commented on test/e2e/framework/framework.go
> +func (f *Framework) GetHealthCheckIpInfo(cluster framework.ClusterIndex) (endpointName, healthCheckIP string) {
```suggestion
func (f *Framework) GetHealthCheckIPInfo(cluster framework.ClusterIndex) (endpointName, healthCheckIP string) {
```

2021-01-08 13:26 UTC, tpantelis commented on test/e2e/framework/framework.go
> +			healthCheckIP, found, err = unstructured.NestedString(spec, "healthCheckIP")
```suggestion
			healthCheckIP, found, err = unstructured.NestedString(endpoint.Object, "spec", "healthCheckIP")
```

2021-01-08 13:26 UTC, tpantelis commented on test/e2e/framework/framework.go
> +func (f *Framework) SetHealthCheckIp(cluster framework.ClusterIndex, ip, endpointName string) {
```suggestion
func (f *Framework) SetHealthCheckIP(cluster framework.ClusterIndex, ip, endpointName string) {
```

2021-01-08 13:26 UTC, tpantelis commented on test/e2e/framework/framework.go
> +	By(fmt.Sprintf("Setting Health Check Ip to %v in cluster %q", ip, framework.TestContext.ClusterIDs[cluster]))
```suggestion
	By(fmt.Sprintf("Setting health check IP cluster %q to %v", framework.TestContext.ClusterIDs[cluster], ip))
```

2021-01-08 13:26 UTC, tpantelis commented on test/e2e/framework/framework.go
> +
This should use `framework.AwaitUntil` just in case.

2021-01-08 13:26 UTC, tpantelis commented on test/e2e/discovery/service_discovery.go
> +	f.SetHealthCheckIp(framework.ClusterC, healthCheckIP, endpointName)
This really should be done in `AfterEach` to ensure we leave it in a good state if the test fails. Call `GetHealthCheckIPInfo` in `BeforeEach`.

2021-01-11 14:37 UTC, tpantelis requested changes

2021-01-11 14:37 UTC, tpantelis commented on test/e2e/framework/framework.go
> +			Expect(endpointName).NotTo(BeNil())
The Name can't be nil.

2021-01-11 14:37 UTC, tpantelis commented on test/e2e/framework/framework.go
> +	}
All of this should be within the check result function of `AwaitUntil`.

2021-01-11 14:37 UTC, tpantelis commented on test/e2e/discovery/service_discovery.go
> +		})
Can you put newlines in between the functions (I'm surprised the linter didn't complain)? Scrunched code is less readable.

2021-01-12 11:14 UTC, vthapar requested changes

2021-01-12 11:14 UTC, vthapar commented on test/e2e/discovery/service_discovery.go
> +	clusterCName := framework.TestContext.ClusterIDs[framework.ClusterC]
Check for number of clusters.

2021-01-12 17:36 UTC, aswinsuryan commented on test/e2e/discovery/service_discovery.go
> +	clusterCName := framework.TestContext.ClusterIDs[framework.ClusterC]
done.

2021-01-13 13:42 UTC, tpantelis requested changes
Looks good - just a couple other suggestions.

2021-01-13 13:42 UTC, tpantelis commented on test/e2e/discovery/service_discovery.go
> +		It("should not resolve the service", func() {
```suggestion
		It("should not resolve that cluster's service IP", func() {
```

2021-01-13 13:42 UTC, tpantelis commented on test/e2e/discovery/service_discovery.go
> +	When("only one of the clusters with a service is healthy", func() {
```suggestion
	When("one of the clusters with a service is not healthy", func() {
```

2021-01-13 13:42 UTC, tpantelis commented on test/e2e/framework/framework.go
> +				}
```suggestion
				if err != nil {
					return false, "", err
				} 
				
				if !found {
					return false, fmt.Sprintf("HealthcheckIP not found in %#v ", endpoint), nil
				}
```

2021-01-13 18:39 UTC, aswinsuryan commented
Depends on https://github.com/submariner-io/submariner-charts/pull/106 , to fix the helm e2e failure.

2021-01-14 18:50 UTC, tpantelis approved these changes

2021-01-15 06:32 UTC, vthapar approved these changes

2021-01-15 08:02 UTC, merged

2022-03-28 19:40 UTC, dfarrell07 commented
This was backported in https://github.com/submariner-io/lighthouse/pull/450.