Adopt admiral API changes
submariner-io/lighthouse pull request #432
Opened 2021-01-12 15:47 UTC by tpantelis

The addition of the `numRequeues` param to callback functions.

2021-01-13 09:11 UTC, aswinsuryan approved these changes

2021-01-13 09:24 UTC, skitt requested changes
Please run `go mod tidy`.

2021-01-13 15:33 UTC, tpantelis commented
> Please run `go mod tidy`.

Done.

2021-01-13 16:39 UTC, tpantelis commented
https://github.com/submariner-io/admiral/pull/172 also adds API changes so we can wait on this until after that is merged

2021-01-14 17:22 UTC, skitt approved these changes

2021-01-14 17:23 UTC, merged