Use env var for ClusterId in lighthouse-coredns
submariner-io/lighthouse pull request #442
Opened 2021-01-28 18:29 UTC by vthapar

Fixes #441

Signed-off-by: Vishal Thapar <5137689+vthapar@users.noreply.github.com>

2021-01-28 18:48 UTC, dfarrell07 approved these changes

2021-01-28 20:02 UTC, tpantelis requested changes

2021-01-29 06:02 UTC, vthapar commented on pkg/gateway/controller.go
> +	err := envconfig.Process("submariner", &corednsSpec)
I initially had couple others but ended up not requiring them after some testing. Will go with `os.Getenv`

2021-01-29 06:08 UTC, vthapar commented on pkg/gateway/controller.go
> +type CorednsSpec struct {
That is the naming convention we been following everywhere else. `submarinerSpec` would be better though as that is the prefix we use.

2021-01-29 09:25 UTC, aswinsuryan approved these changes

2021-01-29 14:06 UTC, tpantelis approved these changes

2021-01-29 14:06 UTC, merged

2022-03-28 20:57 UTC, dfarrell07 commented
This was backported in https://github.com/submariner-io/lighthouse/pull/450.