Include port numbers in ServiceImports
submariner-io/lighthouse pull request #443
Opened 2021-02-01 07:35 UTC by vthapar

Fixes #385

Signed-off-by: Vishal Thapar <5137689+vthapar@users.noreply.github.com>

2021-02-01 08:07 UTC, aswinsuryan reviewed
LGTM

2021-02-01 13:27 UTC, tpantelis requested changes

2021-02-01 13:27 UTC, tpantelis commented on pkg/agent/controller/agent.go
> +	if service.Spec.Ports != nil {
```suggestion
	if len(service.Spec.Ports) > 0 {
```

2021-02-01 14:25 UTC, dfarrell07 approved these changes

2021-02-01 14:49 UTC, tpantelis commented
We should add a unit test case for this (w/ and w/o a port).  @vthapar I can do this in a followup if you want.

2021-02-03 06:27 UTC, vthapar commented
> We should add a unit test case for this (w/ and w/o a port). @vthapar I can do this in a followup if you want.

That would be great. I was planning to do follow up but after I'm done with the submariner serviceexport changes.

2021-02-03 13:33 UTC, tpantelis commented
> > We should add a unit test case for this (w/ and w/o a port). @vthapar I can do this in a followup if you want.
> 
> That would be great. I was planning to do follow up but after I'm done with the submariner serviceexport changes.

OK I'll followup with UTs.

2021-02-03 13:34 UTC, tpantelis approved these changes

2021-02-03 13:34 UTC, merged

2022-03-28 21:00 UTC, dfarrell07 commented
This was backported in https://github.com/submariner-io/lighthouse/pull/450.