Bump all Lighthouse E2E timeouts from 30m to 45m
submariner-io/lighthouse pull request #736
Opened 2022-04-27 15:32 UTC by dfarrell07

It seems like successful jobs can finish in about 20m, but if there are
redeploy/retries then the jobs typically time out in the post mortem.

This is already the timeout used in the main repo.

Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

2022-04-27 16:33 UTC, dfarrell07 commented
It makes sense that the upgrade job is failing, as it's using `curl -L get.submariner.io | VERSION=latest bash` to install the first `subctl` it deploys with, which is 0.12.0 and is impacted by this removed nginx image.

Maybe we need a new `get.submariner.io` target that means "latest build from the latest release branch".

2022-04-27 16:45 UTC, dfarrell07 commented
> Maybe we need a new `get.submariner.io` target that means "latest build from the latest release branch".

I raised https://github.com/submariner-io/get.submariner.io/issues/23 to track.

2022-04-28 01:21 UTC, tpantelis approved these changes

2022-04-28 11:17 UTC, mkolesnik requested changes
No need, see #738

2022-05-02 16:44 UTC, dfarrell07 commented
> No need, see #738

I think this timeout change is independent of that fix. In general, we want the timeout to be long enough for the post mortem to finish when something fails.

2022-05-03 13:13 UTC, mkolesnik commented
> > No need, see #738
> 
> I think this timeout change is independent of that fix. In general, we want the timeout to be long enough for the post mortem to finish when something fails.

Long timeout means longer time of the job in queue and longer time for devs to get feedback.

There's also no guarantee post mortem will actually catch the issue.

The correct way would probably be https://github.com/submariner-io/enhancements/issues/45 which will abort on first failure, which would allow (if no cleanup is being run in tests) for post mortem to gather the info why if failed.

2022-05-04 17:49 UTC, dfarrell07 commented
Okay that's fine, I left a note to clarify the impact of that enhancement on Lighthouse E2E post-mortem.

2022-05-04 17:49 UTC, closed without merging