Use new nettest simpleserver from Shipyard
submariner-io/lighthouse pull request #737
Opened 2022-04-27 17:48 UTC by dfarrell07

See commit messages for details.

2022-04-27 17:49 UTC, dfarrell07 commented
The upgrade tests are still correctly failing, see https://github.com/submariner-io/lighthouse/pull/736#issuecomment-1111213026 for details.

2022-04-27 19:33 UTC, dfarrell07 commented
There are _lots_ of nginx references in Lighthouse. To properly move away from it, even in names, would be a major change.

```
[~/go/src/submariner-io/lighthouse]$ grep -riI --exclude-dir=vendor nginx . | wc -l
324
```

Also wondering if one of these usages is something the `nc` nifty hack doesn't support?

2022-04-27 20:06 UTC, dfarrell07 commented
The E2E failures here are very similar to the ones on Mike's PR with only the Shipyard version bump.

> Failed to  service IP verification. expected execution result "10.2.96.4" to be empty

https://github.com/submariner-io/lighthouse/runs/6198528492?check_suite_focus=true#step:3:2239

> Failed to retrieve Endpoints. endpoints have 0 IPs when expected 3

https://github.com/submariner-io/lighthouse/runs/6198528492?check_suite_focus=true#step:3:2295

> Failed to  service IP verification. expected execution result "10.2.96.4\n10.1.0.6" to be empty

https://github.com/submariner-io/lighthouse/runs/6198528492?check_suite_focus=true#step:3:2584

2022-04-28 11:22 UTC, mkolesnik requested changes, later dismissed
Can you rebase on top of #738 instead of #735 ?

2022-05-03 12:23 UTC, mkolesnik commented on go.mod
> +	github.com/submariner-io/shipyard v0.12.0-m3.0.20220427131749-6b99f918e45e
No need to do this commit, the image is available through Quay and you're just using it

2022-05-03 12:24 UTC, mkolesnik commented on test/e2e/framework/framework.go
> +							Image:           "localhost:5000/nettest:local",
This assumes that it was loaded to a local registry which might not be true when calling `subctl verify`, better use `quay.io/submariner/nettest:devel`

2022-05-04 18:21 UTC, aswinsuryan approved these changes

2022-05-05 07:55 UTC, skitt approved these changes

2022-05-05 11:41 UTC, tpantelis approved these changes

2022-05-05 12:05 UTC, merged

2022-05-05 14:20 UTC, dfarrell07 commented
This is backported here: https://github.com/submariner-io/lighthouse/pull/748